AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/MutableConstant:
  Enabled: false
  
Style/StringLiterals:
  Enabled: false
