#!/usr/bin/env bash
sudo gem uninstall --all --force --executables
sudo gem install bundler
sudo gem install rubocop
sudo gem install rubocop-rspec
sudo gem install rubocop-sequel
sudo gem install puma
sudo gem install sinatra --no-document
