source "https://rubygems.org" do
  gem "capybara"
  gem "openssl"
  gem "rack-test"
  gem "require_all"
  gem "rspec"
  gem "rubocop"
  gem "sequel"
  gem "simplecov"
  gem "sinatra"
  gem "sqlite3"
  gem "thin"
end
